// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktvjsxucoigarjgqchza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dmpzeHVjb2lnYXJqZ3FjaHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDQ2MjksImV4cCI6MjA2MDUyMDYyOX0.fPccHgbaKSqdOZZo0uCUqrxOL_U8og14lHm3ETFwW7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);